clipserve: Silence spurious uninit warning
A user reported:

    src/clipserve.c: In function ‘main’:
    src/clipserve.c:114:5: error: ‘hash’ may be used uninitialized [-Werror=maybe-uninitialized]
      114 |     die_on(cs_content_get(&cs, hash, &content) < 0,
          |     ^
    src/clipserve.c:98:14: note: ‘hash’ was declared here
       98 |     uint64_t hash;
          |              ^

I have no repro on GCC 13.2.1 or clang 17.0.6, but this is clearly just
the compiler being dumb. If:

    expect(str_to_uint64(argv[1], &hash) == 0);

Doesn't terminate the program, then hash is certainly populated. Anyway,
just make it shut up by providing HASH_INVALID.